version: '3'
services:
  # db:
  #   image: mysql:5.7 #mysql5.7が準備されているimageを指定
  #   environment:
  #     - MYSQL_ROOT_PASSWORD=secret #rootのパスワード
  #     - MYSQL_DATABASE=revel #revelデータベースの作成
  #     - MYSQL_USER=revel #revelユーザの作成
  #     - MYSQL_PASSWORD=secret #revelユーザのパスワード
  web:
    build: .
    command: revel run github.com/revel/examples/booking
    volumes:
      - .:/go/src
    ports:
      - 19000:9000
    # depends_on:
    #   - db
